# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: trusty
sudo: required
# OAK-7120: Use specific MongoDB version on travis-ci
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
  - "echo 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org-server=3.6.6"
  - "sudo rm -r /var/lib/mongodb/journal"
  - "sudo rm -r /var/lib/mongodb/diagnostic.data"
  - "sudo rm /var/lib/mongodb/*"
  - "sudo service mongod start"
env:
  - MODULE=oak-jcr
  - MODULE=oak-core
  - MODULE=oak-it
  - MODULE=oak-lucene
  - MODULE=oak-run
  - MODULE=oak-it-osgi
  - MODULE=oak-pojosr
  - MODULE=oak-upgrade
install:  mvn --batch-mode -DskipTests install -pl :${MODULE} -am
script:   mvn --batch-mode clean verify -PintegrationTesting -Dnsfixtures=DOCUMENT_NS -pl :${MODULE}
language: java
jdk:
  - openjdk7
cache:
  directories:
    - $HOME/.m2
notifications:
  email: false